### ISSUE TITLE
Packaged game starts in black screen (no level)

### ISSUE THREAD

**Issue by cellworld** [cellworld/cellword_vr#4]
When game is packaged or ran as standalone, the game runs -> shows loading screen (still kinda ugly) -> we are left in a black space and not in a level. I manually have to run the console command ``` Open LevelName ``` for the level to open. After this happens, everything runs smoothly. 

Project settings are set up correctly. Need to explore what is going on.

**Comment by felixmaldonadoos** [comment]
Fixed on latest merge to main. It was due to not cooking content before packaging the game. Cook > cook content for windows > Package
